api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 10
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        csv: ['text/csv']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
