parameters:

services:
    _defaults:
        autowire: true     
        autoconfigure: true

    _instanceof:
        App\Service\Notification\NotificationHandlerInterface:
            tags: ['app.notification_handler']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\Notification\LogNotificationHandler:
        tags: ['app.notification_handler']
        
    App\Service\Notification\EmailNotificationHandler:
        tags: ['app.notification_handler']

    App\EventSubscriber\ProductNotificationSubscriber:
        arguments:
            $handlers: !tagged_iterator app.notification_handler
        tags:
            - { name: 'kernel.event_subscriber' }

